name: Bug Report

description: Report a bug in the website.

body:
  - type: input
    id: title
    attributes:
      label: Title
      description: A brief summary of the bug
      placeholder: "Enter title"
    validations:
      required: true
      minLength: 5
      maxLength: 100

  - type: input
    id: description
    attributes:
      label: Description
      description: A detailed description of the bug
      placeholder: "Enter description"
      multiline: true
    validations:
      required: true
      minLength: 10
      maxLength: 1000

  - type: input
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: Detailed steps to reproduce the bug
      placeholder: "Enter steps"
      multiline: true
    validations:
      required: true
      minLength: 10
      maxLength: 1000

  - type: select
    id: severity
    attributes:
      label: Severity
      description: Select the severity of the bug
      options:
        - label: High
          value: high
        - label: Medium
          value: medium
        - label: Low
          value: low
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      placeholder: "Enter browser"
    validations:
      required: true
      minLength: 3
      maxLength: 50

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using?
      placeholder: "Enter OS"
    validations:
      required: true
      minLength: 3
      maxLength: 50

  - type: input
    id: url
    attributes:
      label: URL
      description: The URL where the bug occurred
      placeholder: "Enter URL"
    validations:
      required: true
      format: url

  - type: input
    id: screenshot
    attributes:
      label: Screenshot
      description: Optional screenshot of the bug
      placeholder: "Upload screenshot"
      type: file
    validations:
      format: image

  - type: input
    id: log-file
    attributes:
      label: Log File
      description: Optional log file with error details
      placeholder: "Upload log file"
      type: file
    validations:
      format: text

  - type: input
    id: reproduce-on-local
    attributes:
      label: Reproduce on local
      description: Can you reproduce this issue on your local machine?
      placeholder: "Yes/No"
    validations:
      required: true
