name: Feature request
description: Suggest an idea for this project 
labels: ["feature", "triage"]
body:
  - type: input
    id: title
    attributes:
      label: Title
      description: Please share the title of the feature
      placeholder: For E.g, creat 
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: One paragraph explanation of the feature.
    validations:
      required: true
    attributes:
      label:  Feature requirement
      description: Why is this feature of general interest?
      
      
    validations:
      required: true
